addfriend/urls.py
from django.conf.urls import url

from .views import index, message_post

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', message_post, name='add_friend'),
    
]

dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

kilograms/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import addfriend.urls as addfriend
from addfriend.views import index as index_addfriend
import profile_page.urls as profile_page
import update_status.urls as index_update
import update_status.urls as update_status
import dashboard.urls as dashboard

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^addfriend/', include(addfriend,namespace='addfriend')),
    url(r'^profile-page/', include(profile_page, namespace='profile-page')),
	url(r'^update-status/', include(update_status, namespace='update-status')),
    url(r'^$', RedirectView.as_view(url='profile-page/', permanent="true"), name='index'),
    url(r'^dashboard/', include('dashboard.urls',namespace='dashboard')),
]

profile_page/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_todo

urlpatterns = [    
    url(r'^$', index, name='index'),
    url(r'^add_todo', add_todo, name='add_todo'),
]

addfriend/models.py
from django.db import models

class Message(models.Model):
    name = models.CharField(max_length=27)
    # email = models.EmailField()
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message

dashboard/models.py
from django.db import models

# Create your models here.

profile_page/models.py
from django.db import models

# Create your models here.
class ProfileContents(models.Model):
    name = models.CharField(max_length=27)
    birthday = models.DateField()
    gender = models.CharField(max_length=6)
    expertise = models.ManyToManyField('Expertise')
    description = models.TextField()
    email = models.EmailField()
    photo = models.URLField()


    def __str__(self):
        return self.name

class Expertise(models.Model):
    expertise = models.CharField(max_length = 250)

    def __str__(self):
        return str(self.expertise)

update_status/models.py
from django.db import models

class Todo(models.Model):
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

addfriend/forms.py
from django import forms
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    # email = forms.EmailField(required=False, widget=forms.EmailInput(attrs=attrs))
    message = forms.CharField(label='Url', required=False, max_length=100, empty_value='Anonymous', widget=forms.URLInput(attrs=attrs))

 



    # message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

update_status/forms.py
from django import forms

class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Write here...'
    }

   
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

addfriend/views.py
from django.shortcuts import render,redirect
from .forms import Message_Form
from .models import Message
from django.http import HttpResponseRedirect


landing_page_content = 'I am who I am. Not who you think I am. Not who you want me to be. I am me.'
response = {'author': "Arvin Raditya"} #TODO Implement yourname
about_me = ["Never", "Give Up", "On", "My", "Own", "Dream"]

def index(request):
    response['content'] = landing_page_content
    html = 'addfriend/addfriend.html'
    #TODO Implement, isilah dengan 6 kata yang mendeskripsikan anda
    response['about_me'] = about_me
    # return render(request, html, response)
    response['message_form'] = Message_Form
    message = Message.objects.all()
    response['message'] = message

    return render(request, html, response)



def message_post(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] 
        # response['email'] = request.POST['email'] if request.POST['email'] != "" else "Anonymous"
        response['message'] = request.POST['message']
        message = Message(name=response['name'], 
                          message=response['message'])
        message.save()
        html ='addfriend/addfriend.html'
        
        # return redirect('/addfriend/')
    #     return render(request, html, response)
    # else:        
        return HttpResponseRedirect('/addfriend/')


# def message_table(request):
	
#     message = Message.objects.all()
#     response['message'] = message
#     html = 'addfriend/table.html'
#     return redirect('/addfriend/')
    # return render(request, html , response)


# Create your views here.

dashboard/views.py
from django.shortcuts import render
from addfriend.models import Message
from update_status.models import Todo
from profile_page.models import ProfileContents
from profile_page.views import index

# Create your views here.
response = {}
def index(request):
	if ProfileContents.objects.all().count!=0:
		p = ProfileContents.objects.first()
		response['name'] = p.name
		response['photo'] = p.photo
		response['friend'] = 0
		response['feed'] = 0
		if Todo.objects.all().count()!=0:
			todo = Todo.objects.last().description
			status_date = Todo.objects.last().created_date
			status_feeds = Todo.objects.all().count()
			response['latest_post'] = todo
			response['latest_post_date'] = status_date
			response['feed'] = status_feeds
			friends = Message.objects.all().count()
			response['friends'] = friends
	return render(request, "dashboard/dashboard.html", response)

profile_page/views.py
from django.shortcuts import render
from .models import ProfileContents, Expertise

# Create your views here.
response = {}

response['author'] = 'Nabila Fakhirah'

def index(request):
    profile = ProfileContents.objects.create( name = 'Saiton M. Si', birthday = "1996-2-28", gender = 'Male', description = 'I live for photography.', email = 'saitonisms@gmail.com',  photo = 'http://78.media.tumblr.com/8fc11f08dc4e7a1ecf9de7d3a102a8c6/tumblr_oxioilcsKd1wdb06fo5_250.png')
    profile.save()

    e1 = Expertise.objects.create(expertise = 'Photography')
    e1.save()
    e2 = Expertise.objects.create(expertise = 'Dodgeball')
    e2.save()
    e3 = Expertise.objects.create(expertise = 'Karaoke master')
    e3.save()

    profile.expertise.add(e1)
    profile.expertise.add(e2)
    profile.expertise.add(e3)

    response['photo'] = profile.photo
    response['name'] = profile.name
    response['birthday'] = profile.birthday
    response['gender'] = profile.gender
    response['expertise'] = profile.expertise.all()
    response['description'] = profile.description
    response['email'] = profile.email

    html = 'profile_page.html'

    return render(request, html, response)

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Todo_Form
from .models import Todo
from profile_page.models import ProfileContents

# Create your views here.
response = {}
def index(request):    
    response['author'] = "Rai Indhira" #TODO Implement yourname
    profile = ProfileContents.objects.last()
    response['name'] = profile.name
    response['photo'] = profile.photo
    todo = Todo.objects.all()
    todo = Todo.objects.order_by('-id')
    response['todo'] = todo
    html = 'update_status/update_status.html'
    response['todo_form'] = Todo_Form
    return render(request, html, response)
    

def add_todo(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        todo = Todo(description=response['description'])
        todo.save()
        return HttpResponseRedirect('/update-status/')
    else:
        return HttpResponseRedirect('/update-status/')

addfriend/templates/addfriend/addfriend.html
{% extends "addfriend/layout/base.html" %}

{% block content %}



<center>



<!-- 
<hr/>
<section name="bio">
    <h2>Bio</h2>
    <p>
        <strong><em> {{content}} </strong></em>
    </p>    
</section>
<hr/>
</center>
<section name="about_me">
    <h2>List</h2>
    <ul>
        {% for ii in about_me %}
        <li> {{ ii }} </li>
        {% endfor %}
    </ul>
</section>
<hr/> -->


<section name="form">
<center>
        <h1>Add Friend</h1>
        </center>
        <form id="form" method="POST" action="{% url 'addfriend:add_friend' %}">
            {% csrf_token %}
            {{ message_form }}
            <br>
            <button type="submit" class="btn btn-default"> ADD </button>
        </form>
    </section>



    
    <h1 id="juduladd"> Friend List </h1>

    
   
  
    <!-- batas -->


      <div class="flex">
            {% for i in message %}
            {% if i.name == 'Anonymous'%}
             <tr class="warning"> {% else %} <tr class="success">
                {% endif %}
                    <div class="flex-item">
                        <div class="to-do-list">
                            <div class="foto">
                               

                                <img src="http://www.qygjxz.com/data/out/190/5691490-profile-pictures.png" alt="this is my pict" class="img-circle" width = "70px">
                            </div>
                            <div class="nama">
                                {{i.name}}
                            </div>
                            <div class="link">
                                <a href="{{i.message}}"> {{i.message}} </a>
                            </div>

                            <div class="date">
                                {{i.created_date}}
                            </div>
                           
                        </div>
                    </div>
                {% endfor %}
           

 

    {% endblock %}

addfriend/templates/addfriend/form_result.html
{% extends "addfriend/layout/base.html" %}
    {% block title %} Pesan dari {{ name }} {% endblock %}
    {% block content %}
    <textarea readonly rows="5" class="form-control">&quot;{{message}}&quot;-{{name}} 
        by {{ email }}
    </textarea>
    {% endblock %}

    {% block footer %}
        <p> &copy; {{name}} </p>
    {% endblock %}

addfriend/templates/addfriend/layout/addfriend.html
{% extends "addfriend/layout/base.html" %}

    {% block content %}
    <h1>Portofolio</h1>
    <hr/>
    <section name="bio">
        <h2>Bio</h2>
        <!-- <p>
            {{content}}
        </p>    --> 
    </section>
    <hr/>
    <section name="about_me">
        <h2>List</h2>
      <!--   <ul>
            {% for ii in about_me %}
            <li> {{ ii }} </li>
            {% endfor %}
        </ul> -->
    </section>
    <hr/>
    {% endblock %}

addfriend/templates/addfriend/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="add friend">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"> 
    <link rel="stylesheet" type="text/css" href="{% static 'css/addfriend.css' %}" />   

    <title> 
        {% block title %} Add Friend {% endblock %}
    </title>
</head>

<body background="https://i.pinimg.com/236x/77/c2/b4/77c2b450d5f0f60e9d24275c053097aa--home-paint-colors-room-colors.jpg"
;background-repeat : "no-repeat";
background-size : "cover"; >
    <header>
        {% include "addfriend/partials/header.html" %}
    </header>
    <content>



        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "addfriend/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

addfriend/templates/addfriend/partials/footer.html
  <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include 'dashboard/partials/footer.html' %}
        {% endblock %}
    </footer>

addfriend/templates/addfriend/partials/header.html
 {% include "dashboard/partials/navbar.html" %}

addfriend/templates/addfriend/table.html
<!-- {% extends "addfriend/layout/base.html" %}

    {% block title %} Kumpulan Pesan {% endblock %}

    {% block content %}
    <!--  Populate semua isi pesan dari model -->
    <table class="table">
        <thead>
            <th>Nama</th>
            <!-- <th>Email</th> -->
            <th>Link</th>
            <th>Ditambahkan Pada</th>
        </thead>
        <tbody>
            <!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
            {% for i in message %}
            {% if i.name == 'Anonymous'%}
            <tr class="warning"> {% else %} <tr class="success">
                {% endif %}
                <td> {{i.name}} </td>
                <!-- <td> {{i.email}} </td> -->
                <td> <a href="{{i.message}}"> {{i.message}} </a> </td> 
                <td> added {{i.created_date}} </td>
            </tr>             
            {% endfor %}
        </tbody>
    </table>

    {% endblock %} -->

dashboard/templates/dashboard/dashboard.html
{% extends 'dashboard/layout/base.html' %}
{% load staticfiles %}
{% load static %}

{% block content %}
<h1>STATISTIC</h1>
<div class="container-fluid">
	 {% if name %}
	<div class="row">
    <div class="col-sm-offset-2 col-sm-8">
      <div class="col-sm-6 text-center">
        <img class="img-circle" src="http://78.media.tumblr.com/8fc11f08dc4e7a1ecf9de7d3a102a8c6/tumblr_oxioilcsKd1wdb06fo5_250.png" alt="xx" border="0">
      </div>
      <div class="col-sm-6 text-left" id="nama">
        <h1> {{ name }} </h1>
      </div>
    </div>
  		
	</div>
	<div class="row">
 		<div class="col-sm">
 			<h3>{{friend}} Friends</h3>
      		<h3>{{feed}} Feeds</h3>
		</div>
	</div>
	<div class="row">
		<h3>Latest Post :</h3>
      		<div class="status-list">
        		{% if latest_post %}
        		<div class="media-body">
            		<p>{{latest_post}}</p>
            	<div class="status-list-date-added">
                	Posted on {{latest_post_date}}
            	</div>
        		</div>
        {% else %}
          <p> no post yet </p>
        {% endif %}
 			</div>
 		</div>
	{% else %}
    	<h1>4O4</h1>
    	<h3>URL doesn't exist</h3>
  		{% endif %}
	</div>



{% endblock %}

dashboard/templates/dashboard/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 5">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />
    <title>
        {% block title %} Kilograms {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include 'dashboard/partials/navbar.html' %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include 'dashboard/partials/footer.html' %}
        {% endblock %}
    </footer>
</body>
</html>

dashboard/templates/dashboard/partials/footer.html
<div class="container">
 	<p>© 2017<a style="color:#DDE6EA; text-decoration:none;" href="#"> Kilograms Team</a>, All rights reserved 2017-2018.</p>
</div>

dashboard/templates/dashboard/partials/navbar.html
<nav class="navbar navbar-default navbar-fixed-top sticky" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Kilograms</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav" style="float: right" id="navbar-right-menu" >
        <li><a href="/update-status">Status</a></li>
        <li><a href="/profile-page">Profile</a> </li>
        <li><a href="/addfriend">Friends</a></li>
        <li><a href="/dashboard">Stats</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

profile_page/templates/profile_page.html
<!DOCTYPE html>
{% extends "update_status/layout/base.html" %}
{% load static %}

{% block content %}
<title>
    {% block title %} Profile Page By {{author}} {% endblock %}
</title>
<header>
    {% include "dashboard/partials/navbar.html" %}
</header>
    <link rel="stylesheet" href="{% static 'css/profile_page.css' %}">
    <h1> PROFILE PAGE </h1>
    <div id="profile_picture">
        <img src="{{ photo }}" class="center">
    </div>
    <div id="name">
        {{ name }}
    </div>
    <div id="bio">
        <table align="center">
        <tr>
            <td id="subject">Birthday</td>
            <td id="value">{{ birthday }}</td>
        </tr>
        <tr>
            <td id="subject">Gender</td>
            <td id="value">{{ gender }}</td>
        </tr>
        <tr>
            <td id="subject">Expertise</td>
            <td id="value">{% for object in expertise %}
                <div class = "expertise">{{ object }}</div>
            {% endfor %}</td>

        </tr>
        <tr>
            <td id="subject">Description</td>
            <td id="value">{{ description }}</td>
        </tr>
        <tr>
            <td id="subject">Email</td>
            <td id="value">{{ email }}</td>
        </tr>
    </table>
    </div>

    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include 'dashboard/partials/footer.html' %}
        {% endblock %}
    </footer>
{% endblock %}

update_status/templates/update_status/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}" />        
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 5">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->

</head>

<body>
    {% block content %}
    {% endblock %}
    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

update_status/templates/update_status/update_status.html
{% extends "update_status/layout/base.html" %}

{% block content %}
<title>
    {% block title %} Update Status By {{author}} {% endblock %}
</title>
<h1 class="main-title">KILOGRAMS STATUS</h1>
<hr/>
<header>
        {% include 'dashboard/partials/navbar.html' %}
</header>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'update-status:add_todo' %}">
            <h2>Whats Happening?</h2>
            {% csrf_token %}
            {{ todo_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Post">
            <br>
        </form>
    </div>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">TIMELINE</h2>
        <div class="flex">
            {% if todo %}
                {% for data in todo reversed%}
                    <div class="flex-item">
                        <div class="to-do-list">
                            <img src= "{{photo}}"  style = "border-radius : 50px ; height : 50px;" alt="Mountain View" style="width:304px;height:228px;">
                            <div class="to-do-list-title">
                                {{name}}
                            </div>
                            <div class="to-do-list-date-added">
                                {{data.created_date}}
                            </div>
                            <div class="to-do-list-description">
                                {{data.description}}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Todo.
            </div>
            {% endif %}
        </div>
    </div>

</section>
{% endblock %}        